### ISSUE TITLE
Add testcases for `CarPricePredictController.java`

### ISSUE THREAD

**Issue by hgvanpariya** [BestSellingPrice/CarPricePredictorML#3]
Add Testcase for 

https://github.com/BestSellingPrice/CarPricePredictorML/blob/master/src/main/java/com/bestselling/predict/CarPricePredictController.java

**Comment by sylmoss** [comment]
I'd like to implement it.

**Comment by hgvanpariya** [comment]
@sylmoss : Please feel free to add, let me know for any clarifications ...

**Comment by sylmoss** [comment]
https://github.com/BestSellingPrice/CarPricePredictorML/pull/8

Before adding the tests, I've added Lombok to the project.

**Comment by sylmoss** [comment]
Done
